# Generated by Django 5.2.8 on 2025-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airbnb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='address_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_en',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('studio', 'studio')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type_ru',
            field=models.CharField(choices=[('apartment', 'apartment'), ('house', 'house'), ('studio', 'studio')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='rules_en',
            field=models.CharField(choices=[('no_smoking', 'no_smoking'), ('pets_allowed', 'pets_allowed'), ('etc', 'etc')], max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='rules_ru',
            field=models.CharField(choices=[('no_smoking', 'no_smoking'), ('pets_allowed', 'pets_allowed'), ('etc', 'etc')], max_length=64, null=True),
        ),
    ]
